#!/usr/bin/env zsh

# configure zsh history
  HISTFILE=${HOME}/.zsh_history
  HISTSIZE=5500
  SAVEHIST=5000
  setopt extendedhistory        # save timestamp and duration
  setopt histignorealldups      # ignore duplicates
  setopt histignorespace        # ignore lines which start with space
  setopt incappendhistory       # incremental append
  setopt sharehistory           # share history between zsh processes
  setopt HIST_REDUCE_BLANKS     # reduce multiple spaces in a row
  setopt HIST_VERIFY            # when using hist make a newline show the change before executing it
  setopt HIST_EXPIRE_DUPS_FIRST # oldest history event that has a duplicate will be lost before losing a unique event from the list
  setopt HIST_FIND_NO_DUPS      # when searching history entries , do not display duplicates of a line previously found, even if the duplicates are not contiguous

# configure the pushd stack
  DIRSTACKSIZE=20               # set the limit for allowed dirs in the pushd history
  setopt autopushd              # store all cd's in to the pushd stack
  setopt pushdsilent            # do not show the pushd stack
  setopt pushdminus             # swap pushd + and - so that a - removes an entry
  setopt pushdignoredups        # do not store duplicate directories in the pushd stack

# misc options
  setopt autocd                 # allow for changing directory by just typing the path
  setopt extendedglob           # use additional pattern matching features. Treat the `#', `~' and `^' characters as part  of  patterns  for filename  generation, etc.  (An initial unquoted `~' always produces named directory expansion.
  unsetopt notify               # do not immediately report changes in background job status
  unsetopt beep                 # do not beep on errors
  setopt nomatch                # unmatched patterns cause an error
  setopt interactivecomments    # set zsh to ignore inline comments. Used for aliases below to contain comments.
  setopt RM_STAR_WAIT           # 10 second wait if you do something that will delete everything.
  setopt ALIASES                # expand aliases

# editor options
  export EDITOR="vi"

# utf8 locale support
  export LANG=en_US.UTF-8
  export LC_CTYPE=en_US.UTF-8
  export LC_ALL=en_US.UTF-8

# set how keys behave when editing command lines to act like vi
  bindkey -e

# allow spaces to complete command histroy with !
  bindkey -M viins ' ' magic-space

# initialize compinstall
  zstyle :compinstall filename '${HOME}/.files/scripts/zshrc'

  autoload -Uz compinit
  compinit

# disable software flow control so C-s doesn't enable terminal scroll lock, in turn requiring C-q
  stty -ixon

log_debug "00-options custom zsh options set"
