#!/usr/bin/env zsh

# load zsh functions to facilitate colors
autoload -U colors && colors
autoload -U promptinit && promptinit

# zsh prompt configuration
ZSH_PROMPT='%{%f%k%b%}%{%B%F{green}%}%n%{%B%F{blue}%}@%{%B%F{cyan}%}%m%{%B%} %F{yellow}(zsh) %{%b%F{yellow}%}%~%{%B%F{green}%}%f%k%b%}
%{%}%{%}%#%{%f%k%b%} '
ZSH_RPROMPT="%(?.%{%b%F{green}%}.%{%b%F{red}%})%*%{$reset_color%}"

# configure default shell prompt
export PROMPT=${ZSH_PROMPT}
export RPROMPT=${ZSH_RPROMPT}

# configure zsh auto correction prompt
export SPROMPT="Correct $fg[red]%R${reset_color} to $fg[green]%r?${reset_color} (Yes, No, Abort, Edit) "
