#!/usr/bin/env zsh

if hash "zsh" 2>/dev/null; then
  # check if omzsh is already installed or the ignore file has been create
  if [ ! -f ~/.oh-my-zsh/oh-my-zsh.sh ] && [ ! -f ~/.omzsh-ignore ]; then
    # manually clone oh-my-zsh
    git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh

    # setup omz custom theme
    echo PS1=\"$BASH_PS1\">~/.oh-my-zsh/custom/custom.zsh-theme
    echo PROMPT=\'$ZSH_PROMPT\'>>~/.oh-my-zsh/custom/custom.zsh-theme
    echo RPROMPT=\"$ZSH_RPROMPT\">>~/.oh-my-zsh/custom/custom.zsh-theme
  fi
fi
