#!/usr/bin/env zsh

# source oh-my-zsh if found with custom theme
if [ -f ~/.oh-my-zsh/oh-my-zsh.sh ]; then
  export ZSH=$HOME/.oh-my-zsh
  ZSH_THEME="custom"
  plugins=(gitfast vi colorize extract colored-man rsync)
  DISABLE_UPDATE_PROMPT=true
  source $ZSH/oh-my-zsh.sh
fi
