#!/bin/zsh

# ls
alias ls='ls -F --color=auto'
alias lsa='ls -lah'
alias l='ls -la'
alias ll='ls -l'
alias la='ls -lA'
alias sl=ls
alias ls.='ls -d .* --color=auto'

# directory management
alias ..='cd ..'
alias cd..='cd ..'

# mount
alias mount='mount |column -t'

# htop
if (`which htop >/dev/null 2>&1`); then
  alias top='htop'
fi

# diff
if (`which colordiff >/dev/null 2>&1`); then
  alias diff='colordiff'
fi

# wget
alias wget='wget -c' # enable continue of downloads

# tar
alias untar='tar -zxvf'

# rsync
if (`which rsync >/dev/null 2>&1`); then
  alias rsync-copy='rsync -av --progress -h'
  alias rsync-move='rsync -av --progress -h --remove-source-files'
fi

# grep
alias nocomment='grep -Ev '\''^( *)(#|$)'\''' # greps a file for lines without comments
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# dmesg
alias dmesg='dmesg -L auto -T'

